site_name: iKnow 个人资讯库
site_url: https://greennreddddb.github.io/iKnow/
site_description: 自动化资讯收集与整理系统
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
use_directory_urls: false
docs_dir: data
